### ISSUE TITLE
Bypassing bot check with puppeteer-extra

### ISSUE THREAD

**Issue by chaoqing** [go-rod/rod#137]
Maybe it is possible we reuse some work from nodejs community to bypass bot check?
Like
- https://www.npmjs.com/package/puppeteer-extra-plugin-stealth
- https://www.npmjs.com/package/puppeteer-extra-plugin-recaptcha

**Comment by ysmood** [comment]
`puppeteer-extra-plugin-stealth`'s codebase is pretty simple, only hundreds of lines of code, if you work on it, you don't have to do a lot of work, just copy their js into a golang project, you don't have to modify a single line.
Their logic is just run some js on page load.

They use puppeteer plugin interface, so you don't have to read their code that much, their format is pretty static.

We can create a side project under the organization https://github.com/go-rod/. How about calling it `rodx`? `x` means extensions.

I don't feel rod need a plugin interface since we don't heavily depend on callbacks. that's a big advantage over puppeteer. So the extension will work like this:

```go
page := rod.New().Connect().Page("")
rodx.Conceal(page) // anti-bot-detection
page.Navigate("http://a.com")
```

Because their code doesn't change that frequently, we don't have to do auto-sync.

**Comment by ysmood** [comment]
We will let this one open until someone wants to work on it. If anyone wants to work on it please ask us to assign it to you.

**Comment by NormalPunch** [comment]
Check this: https://github.com/go-rod/bypass 

I dumped and parsed the cdp protocol messages then we can use it anywhere. 

BTW, `puppeteer-extra-plugin-stealth` only uses `Page.addScriptToEvaluateOnNewDocument`, but `puppeteer-extra-plugin-recaptcha` maybe not, you can look into it in the same way and welcome your pr.

**Comment by chaoqing** [comment]
@NormalPunch Really fantastic work! Never imagined it can be done this way. Just one question, could the cdp protocol output something pollute the js code?

**Comment by NormalPunch** [comment]
> @NormalPunch Really fantastic work! Never imagined it can be done this way. Just one question, could the cdp protocol output something pollute the js code?

Most of the bypass tricks in cdp implementations are using `Page.addScriptToEvaluateOnNewDocument`, and the param is clean [source](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument).

And yes puppeteer without plugins will add some default scripts too, I filter them [here](https://github.com/go-rod/bypass/blob/21da3f912c40ae5bb0209320eb1cd55b2d51b390/puppeteer-dump/src/stealth.ts#L13-L15). So dont worry, this just tells a way to reuse the puppeteer plugins easily, hope it is helpful.

**Comment by ysmood** [comment]
@chaoqing now it's very easy to use:

```go
```
