### ISSUE TITLE
How to stop EachEvent outside of it?

### ISSUE THREAD

**Issue by n-ozerov** [go-rod/rod#235]
**Rod Version:** v0.67.0

You can use context to stop the listener:

```go
func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	go page.Context(ctx).EachEvent(func(e *proto.PageLifecycleEvent) {
		if e.Name == proto.PageLifecycleEventNameNetworkIdle {
			fmt.Printf("%+v\n", e)
		}
	})()

	page.MustNavigate("http://example.com/")
}
```

maybe we should add a notice in example to not forget to use context if listening events from goroutine?

**Comment by ysmood** [comment]
> maybe we should add a notice in example to not forget to use context if listening events from goroutine?

No, because this goroutine is not created by rod. The implementation of `EachEvent` is blocking, it has no goroutine in it.

You are the one that is creating the goroutine on line 4. It's just a design problem, not a rod problem.

We handling leaking very carefully, check how we use goleak: https://github.com/go-rod/rod/blob/3431735/setup_test.go#L85

**Comment by ysmood** [comment]
BTW, you can use this code to do the same thing, no leak:

```go
func main() {
	page := browser.MustPage("")
	wait := page.MustWaitNavigation()
	page.MustNavigate("http://example.com/")
	wait()
}
```
