### ISSUE TITLE
Running race selector till page loads

### ISSUE THREAD

**Issue by infinitepr0** [go-rod/rod#253]
**Rod Version:** v0.75.0

Is there a way to run a race selector till page loads completely?
Take this example:

- I want to parse some element, say `tr[special-data]` from a webpage.
- The moment the element is found, return the element.
- If the page completes loading, and the element is not found, return `nil` (or `notFoundErr`).

**Comment by ysmood** [comment]
Usually, this is what most people want, since you always know what branches you may face, I personally never have to use WaitLoad:

https://github.com/go-rod/rod/blob/b56609b36850aad9887dc61362a98165fd43de20/examples_test.go#L258-L279


Talking about how to wait navigation load, check the example:

https://github.com/go-rod/rod/blob/b56609b36850aad9887dc61362a98165fd43de20/page_test.go#L310-L315

`Page.WaitNavigation` have many options to choose, usually `PageLifecycleEventNameNetworkAlmostIdle` is what you want,  it's the same as puppetter's `networIdle2`.

**Comment by ysmood** [comment]
You can race operations, rod is thread-safe, just use common way to race in golang, it's not special for rod:

```go
load := make(chan int)
found := make(chan int)

go func() {
	page.MustWaitLoad()
	close(load)
}()
go func() {
	page.MustElement("#btn")
	close(found)
}()

select {
case <-load:
case <-found:
}
```

**Comment by ysmood** [comment]
Another simpler way is to use context, make sure you have learned error handling doc of rod:

```go
page, cancel := page.WithCancel()

go func() {
	page.MustWaitLoad()
	cancel()
}()

page.MustElement("#btn")
```

**Comment by infinitepr0** [comment]
Wow, thanks a lot!
That answers my question.

**Comment by ysmood** [comment]
But both solutions above have a serious bug because the `page.Element` is using polling, if the load event comes during one poll, the result will be unpredictable.

**Comment by ysmood** [comment]
Overall, use load event is never a wise choice, since render the page will take time, and you can never know how long does it take to render the element you want, for example, the page can use js to delay the render of the button: `setTimeout(render, 1000)`.
