### ISSUE TITLE
Let the Page.ElementR support regex flags

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#315]
Such as the case-insensitive flag.

**Comment by infinitepr0** [comment]
Here are some ideas I've considered:
1. Add a variadic string parameter to take regex flags - `page.ElementR(selector, regex, ...flags)`
2. Same as above, but instead of a string parameter,  create a type that specifies the available flags (`regex.CaseInsensitive`, `regex.GlobalSearch` etc)
3. Create a new method `ElementRF` with a flag parameter at the end - `page.ElementRF(selector, regex, flag)`
4. Create (or change the existing) method to directly use regex provided, forcing the user to wrap the existing regex in slashes - `page.ElementR(selector, /regex/)`. Allows to specify flags inline now.

In my evaluation,
- 1 doesn't seem like a good idea, as variadic flags are unnecessary, as the strings are being concatenated.
- 2 seems overkill for a feature as minor as this.
- 3 Would simply clutter/bloat methods, adding little difference between existing methods.
- 4 Seems like the best idea (flexible, covering all regex usecases), tho it would introduce breaking changes.

What do you think about the same? Any better alternatives that I might have missed?

**Comment by ysmood** [comment]
Nice considerations! 4 is best for me too. But it can be optimized: use js directly for the second parameter would make the func backward compatible.

You will use eval: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

The main draw back will be injection attack, we should provide another method like `ElementRegex(selector, regex, flag)` to users when they want to prevent injection.

**Comment by infinitepr0** [comment]
> You will use eval: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
> 
> ```js
> var regCode = '/t/'
> var reg = eval(`new RegExp(${reg})`))
> ```

I'm not very fluent in javascript, but isn't there something obvious missing in the above code?



> The main draw back will be injection attack, we should provide another method like `ElementRegex(selector, regex, flag)` to users when they want to prevent injection.

What about using the `Function()` method provided? [This](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!) says its a better alternative.
Also, looking at the above code, won't any dangerous code be rejected by the `RegExp()` function?

**Comment by ysmood** [comment]
yes, no matter what you use,  eval and Function are the same dangerous, never use any of them if possible. Not just js, learn injection attack in general, you will understand why. `RegExp()` won't help to reject malicious code.

Even pure regex can cause DOS attack, because js regex is not welly design for it. Anyway follow my instructions, don't think too much, it's engineering, not science.
